server:
  port: 8082

spring:
  application:
    name: USER
  cloud:
    consul:
      host: localhost
      port: 8500
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.1.44:3306/memcenter&useUnicode=true&characterEncoding=utf8
#    username: devops
#    password: devops123
#mybatis:
#  type-aliases-package: com.clear2pay.entity.po #指定別名
#  mapper-locations: classpath*:mapper/**/*Mapper.xml

feign:
  client:
    config:
      default:
        connectTimeout: 5000  # 指定Feign客户端连接提供者的超时时限   取决于网络环境
        readTimeout: 5000   # 指定Feign客户端从请求到获取到提供者给出的响应的超时时限  取决于业务逻辑运算时间
      SIMULATOR:
        loggerLevel: BASIC # 指定feign日志调用级别 NONE/BASIC/HEADERS/FULL
  compression:
    request:
      enabled: true   # 开启对请求的压缩
      mime-types: text/xml, application/xml
      min-request-size: 2048   # 指定启用压缩的最小文件大小
    response:
      enabled: true   # 开启对响应的压缩
  hystrix:
    enabled: true # 开启Hystrix支持

logging:
  level:
    com.clear2pay: debug
#SIMULATOR.ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 指定Ribbon负载均衡策略